name: Test and Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Run code tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go vet -v ./...