name: Go
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go vet -v ./...